# Generated by Django 5.0.6 on 2024-05-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_order_cnic_order_first_name_order_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cnic',
        ),
    ]
