# Generated by Django 5.0.6 on 2024-05-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_order_cnic'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cnic',
            field=models.CharField(default='', max_length=100),
        ),
    ]
