# Generated by Django 5.0.6 on 2024-05-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_order_cnic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cnic',
        ),
        migrations.AddField(
            model_name='order',
            name='idcard',
            field=models.CharField(default='', max_length=15),
        ),
    ]
