# Generated by Django 5.0.6 on 2024-05-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_order_cnic_order_idcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='idcard',
            new_name='card',
        ),
    ]
