# Generated by Django 5.0.6 on 2024-05-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_idcard_order_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='card',
            field=models.CharField(max_length=20),
        ),
    ]
