# Generated by Django 5.0.6 on 2024-05-29 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_order_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='borrow_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='order',
            name='borrow_to',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
