# Generated by Django 5.0.6 on 2024-06-07 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_order_borrow_from_order_borrow_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardealer',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.location'),
        ),
    ]
