# Generated by Django 5.0.6 on 2024-06-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_cardealer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cnic_back',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cnic_front',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
