# Generated by Django 5.0.6 on 2024-06-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_order_cnic_back_order_cnic_front'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cnic_back',
            field=models.ImageField(blank=True, null=True, upload_to='cnic_images/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cnic_front',
            field=models.ImageField(blank=True, null=True, upload_to='cnic_images/'),
        ),
    ]
